import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../Components/Navbar'
import Caurosal2 from "../Components/Caurosal2"
import Details from '../Components/Details'
import JoinUs from '../Components/JoinUs'
import Team from '../Components/Team'
import FAQ from '../Components/FAQ'
import Partners from '../Components/Partners'
import Footer from '../Components/Footer'
import Shop from '../Components/Shop'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Caurosal2 />
      <Partners/>
      <Details />
      <JoinUs />
      <Team />
      <Shop/>
      <FAQ/>
      <Footer/>
    </div>
  )
}

export default Home
